### ISSUE TITLE
Circles 

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/gonevis-dash-2#118]
Just like the team, a blog can have circles where the blog authors can create a group/circle of people to share their content with.

Considering the following Circles:

* Friends
* Work

Each of the above groups can have multiple people in them and when the Author is publishing a new post, the author can select what Circles the posts should be shared with.

A Post can have 0 or many circles when being published.

API Endpoints:

* `[GET/POST] /api/v1/sushial/circles/`: All the circles for the blog
* `[GET/DELETE/PATCH/PUT] /api/v1/sushial/circles/<pk>/`: 1 single circle.
* `[POST] /api/v1/sushial/circles/<pk>/members/`: Add new member to the circle.
* `[DELETE] /api/v1/sushial/circles/<pk>/members/`: Remove a member from the circle.
* `[GET] /api/v1/website/site/<pk>/circles/`: Sites circles.

An `Entry` will have 2 new attributes as well:

* Entry.circles: READ (structure of the circles that post has been assigned to.)
* Entry.circle_ids: WRITE (list of circle ids to assign a post to.)

**Adding New Member to Circle**

Only blog followers can be added to circles, meaning you cannot just add people to circles that are not following you.

**Comment by AmirSavand** [comment]
##### Note

We need them in a page to manage all circles and also in post edit so they select circles.
