### ISSUE TITLE
Email Verification Doesn't work

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/gonevis-dash-2#161]
when user click on verify email after signup, they're not get verified

Seems Dash doesn't make the correct request to backend for email verification.

**Comment by ArsalanSavand** [comment]
I investigated and found out that the email verfication has another URL route in our new dashboard and doesn't have a proper UI.
I will change the URL on UI so it matches the verfication link in the email.

Notes:
- Change `user/email-confirmation` URL to `email-verification`
- Add proper UI to indicate that we are verifying the account.

**Comment by Alir3z4** [comment]
Please make this highest priority
Very important to be done, every new account is marked as non-verified.

**Comment by ArsalanSavand** [comment]
I'm working on permissions, after that I will move on to the issue.

**Comment by Alir3z4** [comment]
@ArsalanSavand close this if it's done
