### ISSUE TITLE
Change all blog setting pages

### ISSUE THREAD

**Issue by ArsalanSavand** [SavandBros/gonevis-dash-2#164]
In blog setting pages (General, Appearance and ...) there are API calls being fired multiple times.
And most importantly none of them are lazy loaded.

- [ ] Prevent multiple API calls.
- [ ] Use Lazy-Loading for all components under SettingsComponent.

**Comment by AmirSavand** [comment]
We already discussed this, so you know what to do.

**Comment by ArsalanSavand** [comment]
Blog selection behavior is now changed and ready to be merged.
Only thing left is to make all settings pages lazy-loaded.
