### ISSUE TITLE
Restructure blog selection

### ISSUE THREAD

**Issue by ArsalanSavand** [SavandBros/gonevis-dash-2#169]
Our current blog selection method is raising performance leaking each time user changes a blog or even changes from dashboard view to feed view.

Requirements:
- On blog change, redirect user to a page which shows that blog is changing and after 500 milliseconds, redirect user back to main page.
- Remove all old blog selection method usages.
- Change BlogService completely to have dynamic data information about current selected blog.

**Comment by Alir3z4** [comment]
I agree with this.

Using listener and subscribers to event is pretty expensive, only use them when needed for very small and critical thing, for anything else handle them explicltly and directly.

Please make this happen.
