### ISSUE TITLE
Possibility of undo before deleting a post

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/gonevis-dash-2#181]
I accidentally kicked "delete" button and my post vaporized

This should not be the case at all.
It should work as follow:

* Click on delete button
* Post gets deleted and returns me to posts lists
* Shows me a notification and give me the possibility of Undo at least for 5 seconds (_probably a count down_)
  * if user says undo, cancel deletion
  * if user ignores for 5 second, then delete
   * if user close the message bar, then delete

You can see the same effect in GMail 

![image](https://user-images.githubusercontent.com/591113/73099245-24e6af00-3efc-11ea-958f-74d6a973506f.png)

You can say Post deleted **Undo** x

**Comment by AmirSavand** [comment]
@ArsalanSavand update this ticket, we already got something like this no?

**Comment by ArsalanSavand** [comment]
@AmirSavand We had it in the old version, but we didn't implement it.

**Comment by AmirSavand** [comment]
@Alir3z4 Do we still need it?
