### ISSUE TITLE
Add view password button

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/gonevis-dash-2#184]
I no longer see the "view password" icon on the password input that would relieve my password to see, both on Login and Signup form

**Comment by AmirSavand** [comment]
![image](https://user-images.githubusercontent.com/4629328/73303860-34316980-4228-11ea-81df-9bbf7a5a4076.png)

![image](https://user-images.githubusercontent.com/4629328/73303876-3d223b00-4228-11ea-8926-c0a37c8a22ab.png)
