### ISSUE TITLE
Add back and skip button to start page

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/gonevis-dash-2#185]
It's so frustrating to click back or trying to go back and get to first screen instead of previous screen

**Comment by AmirSavand** [comment]
![image](https://user-images.githubusercontent.com/4629328/73136115-f8957480-405a-11ea-94d2-7f2ffef22165.png)

**Comment by AmirSavand** [comment]
We'll come back at this page later to completely change and improve it.
