### ISSUE TITLE
Comments on dashboard main page don't render HTML content

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/gonevis-dash-2#188]
![image](https://user-images.githubusercontent.com/591113/73100109-f23db600-3efd-11ea-82fe-5f2b80458513.png)

They need to parse and render html.

**Comment by AmirSavand** [comment]
![image](https://user-images.githubusercontent.com/4629328/73120177-193acd00-3f7c-11ea-88b5-ed1be7cf13e4.png)

The same will happen to other pages displaying comments.
