### ISSUE TITLE
Remove popular tags while they're not supported

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/gonevis-dash-2#189]
![image](https://user-images.githubusercontent.com/591113/73100226-2e711680-3efe-11ea-8d45-d90fe8968a0b.png)

We don't have any concrete plan to implement it yet.

**Comment by AmirSavand** [comment]
We need something to show there, I'll think of something.

**Comment by AmirSavand** [comment]
Is there a way to get a list of blogs that authenticated user is subscribed to?

_There's already an endpoint to get the list of users that subscribed to a blog._

**Comment by Alir3z4** [comment]
I don't think so, make a ticket for me in the backend so I can look into it.

**Comment by AmirSavand** [comment]
Closed in https://github.com/SavandBros/gonevis-dash-2/commit/49cc4e46c7d631d27c894f8b5b30767b8318b325

**Comment by AmirSavand** [comment]
Back-end issue ID 1100.

**Comment by Alir3z4** [comment]
> Is there a way to get a list of blogs that authenticated user is subscribed to?

It's done in the backend and now it's on staging 

`api/v1/website/site/?show=subscribed` will return the blogs that user has subscribed to.
