### ISSUE TITLE
Analytical charts

### ISSUE THREAD

**Issue by AmirSavand** [SavandBros/gonevis-dash-2#224]
Let's add some analytics, stats, and charts to the dash.

Users should be able to view charts generally (all posts for example) or by an entity (a single post).

# Dates

- Daily: Query Param `?resolution=day`
- Weekly: Query Param `?resolution=week`
- Monthly: Query Param `?resolution=month`
- Yearly: Query Param `?resolution=year`

# Stats

- View: `/api/v1/site/<uuid:site_pk>/metric/page-stats/`
- Like `/api/v1/site/<uuid:site_pk>/metric/vote-stats/`
- Comment: `/api/v1/site/<uuid:site_pk>/metric/comment-stats/`

To filter by exact entry pass entry id via query param `?entry=`

To bypass limit/pagination, pass the `?limit=` query param and if you noticed there's a next page in the response, you may continuing making calls until you get all of them.

**Comment by Alir3z4** [comment]
@AmirSavand this is ready to fly!

**Comment by AmirSavand** [comment]
![image](https://user-images.githubusercontent.com/4629328/80317068-3d6fa980-880a-11ea-9dbc-67bf7fe93836.png)
