### ISSUE TITLE
Fix design of email confirmation page

### ISSUE THREAD

**Issue by AmirSavand** [SavandBros/gonevis-dash-2#245]
Should be like this page: 
![image](https://user-images.githubusercontent.com/4629328/75113342-34bdf400-565e-11ea-80c4-9685ec84ebac.png)

**Comment by Alir3z4** [comment]
@AmirSavand this is a UX work, I'd prefer you to do it and leave the logic to Arsalan.

**Comment by AmirSavand** [comment]
![image](https://user-images.githubusercontent.com/4629328/75151920-e15cac00-5718-11ea-9c59-e6ad333e80ea.png)

![image](https://user-images.githubusercontent.com/4629328/75151926-e6216000-5718-11ea-994c-ab1d9c0bdc42.png)
