### ISSUE TITLE
After sign up you see dash link instead of feed at navbar

### ISSUE THREAD

**Issue by AmirSavand** [SavandBros/gonevis-dash-2#246]
- [x] After sign up you see dash link instead of feed at navbar
- [ ] After sing up it redirects to update instead of start

![image](https://user-images.githubusercontent.com/4629328/79689662-f52b1700-825e-11ea-8bcf-e90790c8755c.png)

**Comment by Alir3z4** [comment]
@AmirSavand I don't understand this properly.

Please add some more reasoning on this.
Also we need to cover what's the current behavior and what's the expected behavior.
It says them both, but not in a clear way.

**Comment by AmirSavand** [comment]
After sign up, I see this: 
![image](https://user-images.githubusercontent.com/4629328/79689639-d9c00c00-825e-11ea-9927-3c11f38500e5.png)

There's no blog, the link should be "Feed".
