### ISSUE TITLE
Remove authentication handling on the app

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/gonevis-dash-2#373]
# Login/Logout by Session/Cookies instead of JWT

Dash should not handle any JWT anymore, the authentication should be all done on HttpOnly secure cookies both on staging and production.

The most important part of changes will be on every call, `sessionid` and `csrf` (_if exist_) should be send as cookies.

Login method still sends back JWT token and rest of the data but JWT should not be used anymore.

This will help us to easily recognize logged in users both on dash and blogs.

### Endpoints

- Login: /api/v1/account/login/
- Logout: /api/v1/account/logout/

**Comment by AmirSavand** [comment]
@ArsalanSavand make sure to remove any import and usage of cookies.
