### ISSUE TITLE
Show a message after submitting a feedback

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/gonevis-dash-2#381]
When submitting a message via Feedback form, I'd like to get a feedback/message saying "Thank you,  we have received your feedback"

**Comment by AmirSavand** [comment]
![image](https://user-images.githubusercontent.com/4629328/80280185-3c0b8780-870b-11ea-80fb-09485003b753.png)

**Comment by AmirSavand** [comment]
Closes in https://github.com/SavandBros/gonevis-dash-2/commit/e98ea15234eb1d74f8d3ccf8ce9a5ebb5675eed6
