### ISSUE TITLE
No files gets uploaded on the second time

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/gonevis-dash-2#513]
Here's what happened.

1. I've uploaded an image.
2. Image got uploaded (I had to close the progress bar after the image has been uploaded manually #512)
3. Click on the Upload button to upload another file.
4. File dialog opened, selected the file and clicked OK.
5. Nothing happened and file didn't get uplaoded.

**Comment by Alir3z4** [comment]
Note: Checked this on @ArsalanSavand machine on production and couldn't reproduce it, I will try this again on my machine.
Please try to reproduce on other devices. close it if it didn't happen.

**Comment by ArsalanSavand** [comment]
@Alir3z4 I checked now and the bug is that you cannot upload the same file with same name.
We should remove the file references after uploading them.

**Comment by Alir3z4** [comment]
oooooh, good catch
Thanks!
