### ISSUE TITLE
Remove "cname" from the Custom Domains

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/gonevis-dash-2#523]
API has removed the "CNAME" attributes from the custom domains.
User has to simply point their domain DNS records to their blog address.

For example;

User has the alireza.gonevis.com and they decide to add alireza-savand.com to their custom domain.

- User will create a custom domain "alireza-savand.com"
- User adds a CNAME record to their domain pointing to **alireza.gonevis.com**

No matter how many custom domains they add, all of them should point to the original blog address.

For such reason, backend will not keep any cryptic CNAME data anymore and frontend should not show it.
Please modify the message on frontend to properly indicate user has to point their domain CNAME records to their blog address.

**Comment by AmirSavand** [comment]
@Alir3z4 Setting domain returns 500.

**Comment by Alir3z4** [comment]
Please check again now.

**Comment by AmirSavand** [comment]
The help text reamins "Supply domain URLs to your DNS provider for the destination of CNAME or ALIAS records."

The DNS target text is now removed.

![image](https://user-images.githubusercontent.com/4629328/88455662-d355b780-ce7f-11ea-88e4-40fcbfd4acfa.png)
