### ISSUE TITLE
Upload modal

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/gonevis-dash-2#98]
To be used for uploading files and editor as well.

**Comment by Alir3z4** [comment]
I'm not longer able to upload a picture directly within the next editor.
both cover image and insert image only allows me to select an image and if I want to upload, I have to go to Media/Files tab, upload an image and then get back, open image selector modal to select the recently uploaded image.

That's bad UX.
I remember we had it working on old one.

Please implement.

**Comment by AmirSavand** [comment]
@ArsalanSavand didn't you already implement this? Confirm and comment.
